/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthVehiclesIndexRouteImport } from './routes/_auth.vehicles.index'
import { Route as AuthVehiclesVehicleIdRouteRouteImport } from './routes/_auth.vehicles.$vehicleId.route'
import { Route as AuthVehiclesVehicleIdIndexRouteImport } from './routes/_auth.vehicles.$vehicleId.index'
import { Route as AuthVehiclesVehicleIdFuelentryNewRouteImport } from './routes/_auth.vehicles.$vehicleId.fuelentry.new'
import { Route as AuthVehiclesVehicleIdFuelentryFuelEntryIdEditRouteImport } from './routes/_auth.vehicles.$vehicleId.fuelentry.$fuelEntryId.edit'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVehiclesIndexRoute = AuthVehiclesIndexRouteImport.update({
  id: '/vehicles/',
  path: '/vehicles/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVehiclesVehicleIdRouteRoute =
  AuthVehiclesVehicleIdRouteRouteImport.update({
    id: '/vehicles/$vehicleId',
    path: '/vehicles/$vehicleId',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthVehiclesVehicleIdIndexRoute =
  AuthVehiclesVehicleIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthVehiclesVehicleIdRouteRoute,
  } as any)
const AuthVehiclesVehicleIdFuelentryNewRoute =
  AuthVehiclesVehicleIdFuelentryNewRouteImport.update({
    id: '/fuelentry/new',
    path: '/fuelentry/new',
    getParentRoute: () => AuthVehiclesVehicleIdRouteRoute,
  } as any)
const AuthVehiclesVehicleIdFuelentryFuelEntryIdEditRoute =
  AuthVehiclesVehicleIdFuelentryFuelEntryIdEditRouteImport.update({
    id: '/fuelentry/$fuelEntryId/edit',
    path: '/fuelentry/$fuelEntryId/edit',
    getParentRoute: () => AuthVehiclesVehicleIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/vehicles/$vehicleId': typeof AuthVehiclesVehicleIdRouteRouteWithChildren
  '/vehicles': typeof AuthVehiclesIndexRoute
  '/vehicles/$vehicleId/': typeof AuthVehiclesVehicleIdIndexRoute
  '/vehicles/$vehicleId/fuelentry/new': typeof AuthVehiclesVehicleIdFuelentryNewRoute
  '/vehicles/$vehicleId/fuelentry/$fuelEntryId/edit': typeof AuthVehiclesVehicleIdFuelentryFuelEntryIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/vehicles': typeof AuthVehiclesIndexRoute
  '/vehicles/$vehicleId': typeof AuthVehiclesVehicleIdIndexRoute
  '/vehicles/$vehicleId/fuelentry/new': typeof AuthVehiclesVehicleIdFuelentryNewRoute
  '/vehicles/$vehicleId/fuelentry/$fuelEntryId/edit': typeof AuthVehiclesVehicleIdFuelentryFuelEntryIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/vehicles/$vehicleId': typeof AuthVehiclesVehicleIdRouteRouteWithChildren
  '/_auth/vehicles/': typeof AuthVehiclesIndexRoute
  '/_auth/vehicles/$vehicleId/': typeof AuthVehiclesVehicleIdIndexRoute
  '/_auth/vehicles/$vehicleId/fuelentry/new': typeof AuthVehiclesVehicleIdFuelentryNewRoute
  '/_auth/vehicles/$vehicleId/fuelentry/$fuelEntryId/edit': typeof AuthVehiclesVehicleIdFuelentryFuelEntryIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/vehicles/$vehicleId'
    | '/vehicles'
    | '/vehicles/$vehicleId/'
    | '/vehicles/$vehicleId/fuelentry/new'
    | '/vehicles/$vehicleId/fuelentry/$fuelEntryId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/vehicles'
    | '/vehicles/$vehicleId'
    | '/vehicles/$vehicleId/fuelentry/new'
    | '/vehicles/$vehicleId/fuelentry/$fuelEntryId/edit'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_auth/vehicles/$vehicleId'
    | '/_auth/vehicles/'
    | '/_auth/vehicles/$vehicleId/'
    | '/_auth/vehicles/$vehicleId/fuelentry/new'
    | '/_auth/vehicles/$vehicleId/fuelentry/$fuelEntryId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/vehicles/': {
      id: '/_auth/vehicles/'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof AuthVehiclesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/vehicles/$vehicleId': {
      id: '/_auth/vehicles/$vehicleId'
      path: '/vehicles/$vehicleId'
      fullPath: '/vehicles/$vehicleId'
      preLoaderRoute: typeof AuthVehiclesVehicleIdRouteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/vehicles/$vehicleId/': {
      id: '/_auth/vehicles/$vehicleId/'
      path: '/'
      fullPath: '/vehicles/$vehicleId/'
      preLoaderRoute: typeof AuthVehiclesVehicleIdIndexRouteImport
      parentRoute: typeof AuthVehiclesVehicleIdRouteRoute
    }
    '/_auth/vehicles/$vehicleId/fuelentry/new': {
      id: '/_auth/vehicles/$vehicleId/fuelentry/new'
      path: '/fuelentry/new'
      fullPath: '/vehicles/$vehicleId/fuelentry/new'
      preLoaderRoute: typeof AuthVehiclesVehicleIdFuelentryNewRouteImport
      parentRoute: typeof AuthVehiclesVehicleIdRouteRoute
    }
    '/_auth/vehicles/$vehicleId/fuelentry/$fuelEntryId/edit': {
      id: '/_auth/vehicles/$vehicleId/fuelentry/$fuelEntryId/edit'
      path: '/fuelentry/$fuelEntryId/edit'
      fullPath: '/vehicles/$vehicleId/fuelentry/$fuelEntryId/edit'
      preLoaderRoute: typeof AuthVehiclesVehicleIdFuelentryFuelEntryIdEditRouteImport
      parentRoute: typeof AuthVehiclesVehicleIdRouteRoute
    }
  }
}

interface AuthVehiclesVehicleIdRouteRouteChildren {
  AuthVehiclesVehicleIdIndexRoute: typeof AuthVehiclesVehicleIdIndexRoute
  AuthVehiclesVehicleIdFuelentryNewRoute: typeof AuthVehiclesVehicleIdFuelentryNewRoute
  AuthVehiclesVehicleIdFuelentryFuelEntryIdEditRoute: typeof AuthVehiclesVehicleIdFuelentryFuelEntryIdEditRoute
}

const AuthVehiclesVehicleIdRouteRouteChildren: AuthVehiclesVehicleIdRouteRouteChildren =
  {
    AuthVehiclesVehicleIdIndexRoute: AuthVehiclesVehicleIdIndexRoute,
    AuthVehiclesVehicleIdFuelentryNewRoute:
      AuthVehiclesVehicleIdFuelentryNewRoute,
    AuthVehiclesVehicleIdFuelentryFuelEntryIdEditRoute:
      AuthVehiclesVehicleIdFuelentryFuelEntryIdEditRoute,
  }

const AuthVehiclesVehicleIdRouteRouteWithChildren =
  AuthVehiclesVehicleIdRouteRoute._addFileChildren(
    AuthVehiclesVehicleIdRouteRouteChildren,
  )

interface AuthRouteChildren {
  AuthVehiclesVehicleIdRouteRoute: typeof AuthVehiclesVehicleIdRouteRouteWithChildren
  AuthVehiclesIndexRoute: typeof AuthVehiclesIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthVehiclesVehicleIdRouteRoute: AuthVehiclesVehicleIdRouteRouteWithChildren,
  AuthVehiclesIndexRoute: AuthVehiclesIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
