/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthVehiclesIndexRouteImport } from './routes/_auth/vehicles/index'
import { Route as AuthVehiclesVehicleIdIndexRouteImport } from './routes/_auth/vehicles/$vehicleId/index'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVehiclesIndexRoute = AuthVehiclesIndexRouteImport.update({
  id: '/vehicles/',
  path: '/vehicles/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVehiclesVehicleIdIndexRoute =
  AuthVehiclesVehicleIdIndexRouteImport.update({
    id: '/vehicles/$vehicleId/',
    path: '/vehicles/$vehicleId/',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/vehicles': typeof AuthVehiclesIndexRoute
  '/vehicles/$vehicleId': typeof AuthVehiclesVehicleIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/vehicles': typeof AuthVehiclesIndexRoute
  '/vehicles/$vehicleId': typeof AuthVehiclesVehicleIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/vehicles/': typeof AuthVehiclesIndexRoute
  '/_auth/vehicles/$vehicleId/': typeof AuthVehiclesVehicleIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/vehicles' | '/vehicles/$vehicleId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/vehicles' | '/vehicles/$vehicleId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_auth/vehicles/'
    | '/_auth/vehicles/$vehicleId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/vehicles/': {
      id: '/_auth/vehicles/'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof AuthVehiclesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/vehicles/$vehicleId/': {
      id: '/_auth/vehicles/$vehicleId/'
      path: '/vehicles/$vehicleId'
      fullPath: '/vehicles/$vehicleId'
      preLoaderRoute: typeof AuthVehiclesVehicleIdIndexRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthVehiclesIndexRoute: typeof AuthVehiclesIndexRoute
  AuthVehiclesVehicleIdIndexRoute: typeof AuthVehiclesVehicleIdIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthVehiclesIndexRoute: AuthVehiclesIndexRoute,
  AuthVehiclesVehicleIdIndexRoute: AuthVehiclesVehicleIdIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
